{% set name = "xarray-topo" %}
{% set version = "0.0.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/xarray-topo-{{ version }}.tar.gz
  sha256: ecac7806a3238c85a91d80e71d53e649a261132e56cb004c01cd9bc859fed223

build:
  number: 1001
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}
    - numpy
    - xarray >=0.10.0
    - xarray-simlab >=0.2.0
    - numba >=0.35.0

test:
  requires:
    - python {{ python_min }}
    - pip
  imports:
    - xtopo
    - xtopo.models
    - xtopo.algos
  commands:
    - pip check

about:
  home: https://gitext.gfz-potsdam.de/sec55-public/xarray-topo
  license: BSD-3-Clause
  license_file: LICENSE
  summary: 'xarray extension for for topographic analysis and modeling'

extra:
  recipe-maintainers:
    - benbovy
